### ISSUE TITLE
Issue in listview

### ISSUE THREAD

**Issue by vikash159** [channguyen/animated-dot-view#1]
Doesnt work in listview....

**Comment by roxrook** [comment]
Thanks for reporting!
Could you elaborate a bit? Was it invisible?

**Comment by vikash159** [comment]
actually when i try to put inside relative-layout and its invisible, but inside linear-layout its appears and animating. im using this in listview child...

**Comment by roxrook** [comment]
@vikash159 : Check out my latest commit, let me know if that works out for you. Will upgrade maven later when I have time.
